name: CI

on: pull_request

jobs:
  proto-lint:
    name: proto lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Regenerate Proto code
        run: make proto-go

      - name: Proto lint
        run: make proto-lint

      - name: Ensure generated code is checked in
        # Fail the job if there are any uncommitted changes (ensures generated code is checked in)
        run: |
          git diff --quiet || (echo "Error: Uncommitted changes detected. Please commit generated code."; git status; exit 1)

  thrift-compile:
    name: thrift compile
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install thrift compiler
        run: |
          sudo apt-get update
          sudo apt-get install -y thrift-compiler

      - name: Thrift lint
        run: make thriftlint
